apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: webhook-server
    app.kubernetes.io/part-of: podexec-defender
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhookserver-tls
  name: webhook-server
  namespace: podexec-defender
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: webhook-server
  selector:
    app.kubernetes.io/name: webhook-server
    app.kubernetes.io/part-of: podexec-defender
  type: ClusterIP
