apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: webhook-server
    app.kubernetes.io/part-of: podexec-defender
  name: webhook-server
  namespace: podexec-defender
